/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:cbb98c46-9df4-49ec-bb61-f73b62dad964",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_bKWc9TEcq",
    "aws_user_pools_web_client_id": "2m3q8n67s90dhu00pn3hvphbh7",
    "oauth": {}
};


export default awsmobile;
