/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://zmt2jrt3drhh5dql6i4r4t7q2y.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2pllurnobvctxg47ixeg4fh6ne",
    "aws_cognito_identity_pool_id": "eu-west-1:cbb98c46-9df4-49ec-bb61-f73b62dad964",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_bKWc9TEcq",
    "aws_user_pools_web_client_id": "2m3q8n67s90dhu00pn3hvphbh7",
    "oauth": {}
};


export default awsmobile;
